### ISSUE TITLE
Support any arity

### ISSUE THREAD

**Issue by eproxus** [eproxus/future#2]
We should support functions of any arity (not just one):

``` Elixir
f = Future.new fun x, y -> x + y end
assert 3 == Future.value f.(1, 2)
```

Tried to implement this using macros, but couldn't really make it work together. I think we need a macro that goes from:

``` Elixir
fn x, y ->
  x + y
end
```

To:

``` Elixir
fn v1, v2 ->
  ...
  f = fn x, y -> x + y end
  f.(v1, v2)
  ..
end
```

Where `...` is the process spawning etc.

Currently, this works:

``` Elixir
quote do
  elem(:erlang.fun_info(unquote(func), :arity), 1)
end
```

Which gives us the arity, but I can't figure out how to build a dynamic fun with this. Generating a list of arguments is easy:

``` Elixir
Enum.map(1..arity, fn n ->{binary_to_symbol("v#{n}"), [], Elixir} end)
```

But where to go next?

**Comment by josephwilk** [comment]
The secret is in `unquote_splicing` (http://elixir-lang.org/docs/stable/Kernel.SpecialForms.html#unquote_splicing/1) which turns a list of args into comma delimited args that can be used as function arguments. 

My extraction of the arg parameter count is a lot uglier.
